#![no_std]

use esp_hal::{delay::Delay, gpio::OutputPin, mcpwm::{operator::PwmPin, PwmPeripheral}};
use esp_println::print;

pub struct Servo<'d, Pin: OutputPin, PWM: PwmPeripheral, const OP: u8, const IS_A: bool> {
     pin: PwmPin<'d, Pin, PWM, OP, IS_A>,
}

enum Angle {
    Zero,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,
    Ten,
    Eleven,
    Twelve,
    Thirteen,
    Fourteen,
    Fifteen,
    Sixteen,
    Seventeen,
    Eighteen,
    Nineteen,
    Twenty,
    TwentyOne,
    TwentyTwo,
    TwentyThree,
    TwentyFour,
    TwentyFive,
    TwentySix,
    TwentySeven,
    TwentyEight,
    TwentyNine,
    Thirty,
    ThirtyOne,
    ThirtyTwo,
    ThirtyThree,
    ThirtyFour,
    ThirtyFive,
    ThirtySix,
    ThirtySeven,
    ThirtyEight,
    ThirtyNine,
    Fourty,
    FourtyOne,
    FourtyTwo,
    FourtyThree,
    FourtyFour,
    FourtyFive,
    FourtySix,
    FourtySeven,
    FourtyEight,
    FourtyNine,
    Fifty,
    FiftyOne,
    FiftyTwo,
    FiftyThree,
    FiftyFour,
    FiftyFive,
    FiftySix,
    FiftySeven,
    FiftyEight,
    FiftyNine,
    Sixty,
    SixtyOne,
    SixtyTwo,
    SixtyThree,
    SixtyFour,
    SixtyFive,
    SixtySix,
    SixtySeven,
    SixtyEight,
    SixtyNine,
    Seventy,
    SeventyOne,
    SeventyTwo,
    SeventyThree,
    SeventyFour,
    SeventyFive,
    SeventySix,
    SeventySeven,
    SeventyEight,
    SeventyNine,
    Eighty,
    EightyOne,
    EightyTwo,
    EightyThree,
    EightyFour,
    EightyFive,
    EightySix,
    EightySeven,
    EightyEight,
    EightyNine,
    Ninety,
    NinetyOne,
    NinetyTwo,
    NinetyThree,
    NinetyFour,
    NinetyFive,
    NinetySix,
    NinetySeven,
    NinetyEight,
    NinetyNine,
    OneHundred,
    OneHundredOne,
    OneHundredTwo,
    OneHundredThree,
    OneHundredFour,
    OneHundredFive,
    OneHundredSix,
    OneHundredSeven,
    OneHundredEight,
    OneHundredNine,
    OneHundredTen,
    OneHundredEleven,
    OneHundredTwelve,
    OneHundredThirteen,
    OneHundredFourteen,
    OneHundredFifteen,
    OneHundredSixteen,
    OneHundredSeventeen,
    OneHundredEighteen,
    OneHundredNineteen,
    OneHundredTwenty,
    OneHundredTwentyOne,
    OneHundredTwentyTwo,
    OneHundredTwentyThree,
    OneHundredTwentyFour,
    OneHundredTwentyFive,
    OneHundredTwentySix,
    OneHundredTwentySeven,
    OneHundredTwentyEight,
    OneHundredTwentyNine,
    OneHundredThirty,
    OneHundredThirtyOne,
    OneHundredThirtyTwo,
    OneHundredThirtyThree,
    OneHundredThirtyFour,
    OneHundredThirtyFive,
    OneHundredThirtySix,
    OneHundredThirtySeven,
    OneHundredThirtyEight,
    OneHundredThirtyNine,
    OneHundredFourty,
    OneHundredFourtyOne,
    OneHundredFourtyTwo,
    OneHundredFourtyThree,
    OneHundredFourtyFour,
    OneHundredFourtyFive,
    OneHundredFourtySix,
    OneHundredFourtySeven,
    OneHundredFourtyEight,
    OneHundredFourtyNine,
    OneHundredFifty,
    OneHundredFiftyOne,
    OneHundredFiftyTwo,
    OneHundredFiftyThree,
    OneHundredFiftyFour,
    OneHundredFiftyFive,
    OneHundredFiftySix,
    OneHundredFiftySeven,
    OneHundredFiftyEight,
    OneHundredFiftyNine,
    OneHundredSixty,
    OneHundredSixtyOne,
    OneHundredSixtyTwo,
    OneHundredSixtyThree,
    OneHundredSixtyFour,
    OneHundredSixtyFive,
    OneHundredSixtySix,
    OneHundredSixtySeven,
    OneHundredSixtyEight,
    OneHundredSixtyNine,
    OneHundredSeventy,
    OneHundredSeventyOne,
    OneHundredSeventyTwo,
    OneHundredSeventyThree,
    OneHundredSeventyFour,
    OneHundredSeventyFive,
    OneHundredSeventySix,
    OneHundredSeventySeven,
    OneHundredSeventyEight,
    OneHundredSeventyNine,
    OneHundredEighty,
}


impl Angle {
    fn value(&self) -> u16 {
        match *self {
            Angle::Zero => 399,
            Angle::One => 410,
            Angle::Two => 421,
            Angle::Three => 432,
            Angle::Four => 443,
            Angle::Five => 454,
            Angle::Six => 465,
            Angle::Seven => 476,
            Angle::Eight => 487,
            Angle::Nine => 498,
            Angle::Ten => 509,
            Angle::Eleven => 520,
            Angle::Twelve => 531,
            Angle::Thirteen => 542,
            Angle::Fourteen => 553,
            Angle::Fifteen => 564,
            Angle::Sixteen => 575,
            Angle::Seventeen => 586,
            Angle::Eighteen => 597,
            Angle::Nineteen => 608,
            Angle::Twenty => 619,
            Angle::TwentyOne => 630,
            Angle::TwentyTwo => 641,
            Angle::TwentyThree => 652,
            Angle::TwentyFour => 663,
            Angle::TwentyFive => 674,
            Angle::TwentySix => 685,
            Angle::TwentySeven => 696,
            Angle::TwentyEight => 707,
            Angle::TwentyNine => 718,
            Angle::Thirty => 729,
            Angle::ThirtyOne => 740,
            Angle::ThirtyTwo => 751,
            Angle::ThirtyThree => 762,
            Angle::ThirtyFour => 773,
            Angle::ThirtyFive => 784,
            Angle::ThirtySix => 795,
            Angle::ThirtySeven => 806,
            Angle::ThirtyEight => 817,
            Angle::ThirtyNine => 828,
            Angle::Fourty => 839,
            Angle::FourtyOne => 850,
            Angle::FourtyTwo => 861,
            Angle::FourtyThree => 872,
            Angle::FourtyFour => 883,
            Angle::FourtyFive => 894,
            Angle::FourtySix => 905,
            Angle::FourtySeven => 916,
            Angle::FourtyEight => 927,
            Angle::FourtyNine => 938,
            Angle::Fifty => 949,
            Angle::FiftyOne => 960,
            Angle::FiftyTwo => 971,
            Angle::FiftyThree => 982,
            Angle::FiftyFour => 993,
            Angle::FiftyFive => 1004,
            Angle::FiftySix => 1015,
            Angle::FiftySeven => 1026,
            Angle::FiftyEight => 1037,
            Angle::FiftyNine => 1048,
            Angle::Sixty => 1059,
            Angle::SixtyOne => 1070,
            Angle::SixtyTwo => 1081,
            Angle::SixtyThree => 1092,
            Angle::SixtyFour => 1103,
            Angle::SixtyFive => 1114,
            Angle::SixtySix => 1125,
            Angle::SixtySeven => 1136,
            Angle::SixtyEight => 1147,
            Angle::SixtyNine => 1158,
            Angle::Seventy => 1169,
            Angle::SeventyOne => 1180,
            Angle::SeventyTwo => 1191,
            Angle::SeventyThree => 1102,
            Angle::SeventyFour => 1113,
            Angle::SeventyFive => 1124,
            Angle::SeventySix => 1135,
            Angle::SeventySeven => 1146,
            Angle::SeventyEight => 1157,
            Angle::SeventyNine => 1168,
            Angle::Eighty => 1179,
            Angle::EightyOne => 1190,
            Angle::EightyTwo => 1201,
            Angle::EightyThree => 1212,
            Angle::EightyFour => 1223,
            Angle::EightyFive => 1234,
            Angle::EightySix => 1245,
            Angle::EightySeven => 1256,
            Angle::EightyEight => 1267,
            Angle::EightyNine => 1278,
            Angle::Ninety => 1289,
            Angle::NinetyOne => 1300,
            Angle::NinetyTwo => 1311,
            Angle::NinetyThree => 1322,
            Angle::NinetyFour => 1333,
            Angle::NinetyFive => 1344,
            Angle::NinetySix => 1355,
            Angle::NinetySeven => 1366,
            Angle::NinetyEight => 1377,
            Angle::NinetyNine => 1388,
            Angle::OneHundred => 1399,
            Angle::OneHundredOne => 1410,
            Angle::OneHundredTwo => 1421,
            Angle::OneHundredThree => 1432,
            Angle::OneHundredFour => 1443,
            Angle::OneHundredFive => 1454,
            Angle::OneHundredSix => 1465,
            Angle::OneHundredSeven => 1476,
            Angle::OneHundredEight => 1487,
            Angle::OneHundredNine => 1498,
            Angle::OneHundredTen => 1509,
            Angle::OneHundredEleven => 1520,
            Angle::OneHundredTwelve => 1531,
            Angle::OneHundredThirteen => 1542,
            Angle::OneHundredFourteen => 1553,
            Angle::OneHundredFifteen => 1564,
            Angle::OneHundredSixteen => 1575,
            Angle::OneHundredSeventeen => 1586,
            Angle::OneHundredEighteen => 1597,
            Angle::OneHundredNineteen => 1608,
            Angle::OneHundredTwenty => 1619,
            Angle::OneHundredTwentyOne => 1630,
            Angle::OneHundredTwentyTwo => 1641,
            Angle::OneHundredTwentyThree => 1652,
            Angle::OneHundredTwentyFour => 1663,
            Angle::OneHundredTwentyFive => 1674,
            Angle::OneHundredTwentySix => 1685,
            Angle::OneHundredTwentySeven => 1696,
            Angle::OneHundredTwentyEight => 1707,
            Angle::OneHundredTwentyNine => 1718,
            Angle::OneHundredThirty => 1729,
            Angle::OneHundredThirtyOne => 1740,
            Angle::OneHundredThirtyTwo => 1751,
            Angle::OneHundredThirtyThree => 1762,
            Angle::OneHundredThirtyFour => 1773,
            Angle::OneHundredThirtyFive => 1784,
            Angle::OneHundredThirtySix => 1795,
            Angle::OneHundredThirtySeven => 1806,
            Angle::OneHundredThirtyEight => 1817,
            Angle::OneHundredThirtyNine => 1828,
            Angle::OneHundredFourty => 1839,
            Angle::OneHundredFourtyOne => 1850,
            Angle::OneHundredFourtyTwo => 1861,
            Angle::OneHundredFourtyThree => 1872,
            Angle::OneHundredFourtyFour => 1883,
            Angle::OneHundredFourtyFive => 1894,
            Angle::OneHundredFourtySix => 1905,
            Angle::OneHundredFourtySeven => 1916,
            Angle::OneHundredFourtyEight => 1927,
            Angle::OneHundredFourtyNine => 1938,
            Angle::OneHundredFifty => 1949,
            Angle::OneHundredFiftyOne => 1960,
            Angle::OneHundredFiftyTwo => 1971,
            Angle::OneHundredFiftyThree => 1982,
            Angle::OneHundredFiftyFour => 1993,
            Angle::OneHundredFiftyFive => 2004,
            Angle::OneHundredFiftySix => 2015,
            Angle::OneHundredFiftySeven => 2026,
            Angle::OneHundredFiftyEight => 2037,
            Angle::OneHundredFiftyNine => 2048,
            Angle::OneHundredSixty => 2059,
            Angle::OneHundredSixtyOne => 2070,
            Angle::OneHundredSixtyTwo => 2081,
            Angle::OneHundredSixtyThree => 2092,
            Angle::OneHundredSixtyFour => 2103,
            Angle::OneHundredSixtyFive => 2114,
            Angle::OneHundredSixtySix => 2125,
            Angle::OneHundredSixtySeven => 2136,
            Angle::OneHundredSixtyEight => 2147,
            Angle::OneHundredSixtyNine => 2158,
            Angle::OneHundredSeventy => 2169,
            Angle::OneHundredSeventyOne => 2180,
            Angle::OneHundredSeventyTwo => 2191,
            Angle::OneHundredSeventyThree => 2102,
            Angle::OneHundredSeventyFour => 2113,
            Angle::OneHundredSeventyFive => 2124,
            Angle::OneHundredSeventySix => 2135,
            Angle::OneHundredSeventySeven => 2146,
            Angle::OneHundredSeventyEight => 2157,
            Angle::OneHundredSeventyNine => 2168,
            Angle::OneHundredEighty => 2399,
        }
    }
}

impl<'d, Pin: OutputPin, PWM: PwmPeripheral, const OP: u8, const IS_A: bool> Servo<'d, Pin, PWM, OP, IS_A>
{
    pub fn new(pin: PwmPin<'d, Pin, PWM, OP, IS_A>) -> Self {
        Servo { pin: pin }
    }

    // set position of motor from 0 degrees to 180 degrees
    pub fn set_position(&mut self, position: u16) {
        match position {
            0 => self.pin.set_timestamp(Angle::Zero.value()),
            1 => self.pin.set_timestamp(Angle::One.value()),
            2 => self.pin.set_timestamp(Angle::Two.value()),
            3 => self.pin.set_timestamp(Angle::Three.value()),
            4 => self.pin.set_timestamp(Angle::Four.value()),
            5 => self.pin.set_timestamp(Angle::Five.value()),
            6 => self.pin.set_timestamp(Angle::Six.value()),
            7 => self.pin.set_timestamp(Angle::Seven.value()),
            8 => self.pin.set_timestamp(Angle::Eight.value()),
            9 => self.pin.set_timestamp(Angle::Nine.value()),
            10 => self.pin.set_timestamp(Angle::Ten.value()),
            11 => self.pin.set_timestamp(Angle::Eleven.value()),
            12 => self.pin.set_timestamp(Angle::Twelve.value()),
            13 => self.pin.set_timestamp(Angle::Thirteen.value()),
            14 => self.pin.set_timestamp(Angle::Fourteen.value()),
            15 => self.pin.set_timestamp(Angle::Fifteen.value()),
            16 => self.pin.set_timestamp(Angle::Sixteen.value()),
            17 => self.pin.set_timestamp(Angle::Seventeen.value()),
            18 => self.pin.set_timestamp(Angle::Eighteen.value()),
            19 => self.pin.set_timestamp(Angle::Nineteen.value()),
            20 => self.pin.set_timestamp(Angle::Twenty.value()),
            21 => self.pin.set_timestamp(Angle::TwentyOne.value()),
            22 => self.pin.set_timestamp(Angle::TwentyTwo.value()),
            23 => self.pin.set_timestamp(Angle::TwentyThree.value()),
            24 => self.pin.set_timestamp(Angle::TwentyFour.value()),
            25 => self.pin.set_timestamp(Angle::TwentyFive.value()),
            26 => self.pin.set_timestamp(Angle::TwentySix.value()),
            27 => self.pin.set_timestamp(Angle::TwentySeven.value()),
            28 => self.pin.set_timestamp(Angle::TwentyEight.value()),
            29 => self.pin.set_timestamp(Angle::TwentyNine.value()),
            30 => self.pin.set_timestamp(Angle::Thirty.value()),
            31 => self.pin.set_timestamp(Angle::ThirtyOne.value()),
            32 => self.pin.set_timestamp(Angle::ThirtyTwo.value()),
            33 => self.pin.set_timestamp(Angle::ThirtyThree.value()),
            34 => self.pin.set_timestamp(Angle::ThirtyFour.value()),
            35 => self.pin.set_timestamp(Angle::ThirtyFive.value()),
            36 => self.pin.set_timestamp(Angle::ThirtySix.value()),
            37 => self.pin.set_timestamp(Angle::ThirtySeven.value()),
            38 => self.pin.set_timestamp(Angle::ThirtyEight.value()),
            39 => self.pin.set_timestamp(Angle::ThirtyNine.value()),
            40 => self.pin.set_timestamp(Angle::Fourty.value()),
            41 => self.pin.set_timestamp(Angle::FourtyOne.value()),
            42 => self.pin.set_timestamp(Angle::FourtyTwo.value()),
            43 => self.pin.set_timestamp(Angle::FourtyThree.value()),
            44 => self.pin.set_timestamp(Angle::FourtyFour.value()),
            45 => self.pin.set_timestamp(Angle::FourtyFive.value()),
            46 => self.pin.set_timestamp(Angle::FourtySix.value()),
            47 => self.pin.set_timestamp(Angle::FourtySeven.value()),
            48 => self.pin.set_timestamp(Angle::FourtyEight.value()),
            49 => self.pin.set_timestamp(Angle::FourtyNine.value()),
            50 => self.pin.set_timestamp(Angle::Fifty.value()),
            51 => self.pin.set_timestamp(Angle::FiftyOne.value()),
            52 => self.pin.set_timestamp(Angle::FiftyTwo.value()),
            53 => self.pin.set_timestamp(Angle::FiftyThree.value()),
            54 => self.pin.set_timestamp(Angle::FiftyFour.value()),
            55 => self.pin.set_timestamp(Angle::FiftyFive.value()),
            56 => self.pin.set_timestamp(Angle::FiftySix.value()),
            57 => self.pin.set_timestamp(Angle::FiftySeven.value()),
            58 => self.pin.set_timestamp(Angle::FiftyEight.value()),
            59 => self.pin.set_timestamp(Angle::FiftyNine.value()),
            60 => self.pin.set_timestamp(Angle::Sixty.value()),
            61 => self.pin.set_timestamp(Angle::SixtyOne.value()),
            62 => self.pin.set_timestamp(Angle::SixtyTwo.value()),
            63 => self.pin.set_timestamp(Angle::SixtyThree.value()),
            64 => self.pin.set_timestamp(Angle::SixtyFour.value()),
            65 => self.pin.set_timestamp(Angle::SixtyFive.value()),
            66 => self.pin.set_timestamp(Angle::SixtySix.value()),
            67 => self.pin.set_timestamp(Angle::SixtySeven.value()),
            68 => self.pin.set_timestamp(Angle::SixtyEight.value()),
            69 => self.pin.set_timestamp(Angle::SixtyNine.value()),
            70 => self.pin.set_timestamp(Angle::Seventy.value()),
            71 => self.pin.set_timestamp(Angle::SeventyOne.value()),
            72 => self.pin.set_timestamp(Angle::SeventyTwo.value()),
            73 => self.pin.set_timestamp(Angle::SeventyThree.value()),
            74 => self.pin.set_timestamp(Angle::SeventyFour.value()),
            75 => self.pin.set_timestamp(Angle::SeventyFive.value()),
            76 => self.pin.set_timestamp(Angle::SeventySix.value()),
            77 => self.pin.set_timestamp(Angle::SeventySeven.value()),
            78 => self.pin.set_timestamp(Angle::SeventyEight.value()),
            79 => self.pin.set_timestamp(Angle::SeventyNine.value()),
            80 => self.pin.set_timestamp(Angle::Eighty.value()),
            81 => self.pin.set_timestamp(Angle::EightyOne.value()),
            82 => self.pin.set_timestamp(Angle::EightyTwo.value()),
            83 => self.pin.set_timestamp(Angle::EightyThree.value()),
            84 => self.pin.set_timestamp(Angle::EightyFour.value()),
            85 => self.pin.set_timestamp(Angle::EightyFive.value()),
            86 => self.pin.set_timestamp(Angle::EightySix.value()),
            87 => self.pin.set_timestamp(Angle::EightySeven.value()),
            88 => self.pin.set_timestamp(Angle::EightyEight.value()),
            89 => self.pin.set_timestamp(Angle::EightyNine.value()),
            90 => self.pin.set_timestamp(Angle::Ninety.value()),
            91 => self.pin.set_timestamp(Angle::NinetyOne.value()),
            92 => self.pin.set_timestamp(Angle::NinetyTwo.value()),
            93 => self.pin.set_timestamp(Angle::NinetyThree.value()),
            94 => self.pin.set_timestamp(Angle::NinetyFour.value()),
            95 => self.pin.set_timestamp(Angle::NinetyFive.value()),
            96 => self.pin.set_timestamp(Angle::NinetySix.value()),
            97 => self.pin.set_timestamp(Angle::NinetySeven.value()),
            98 => self.pin.set_timestamp(Angle::NinetyEight.value()),
            99 => self.pin.set_timestamp(Angle::NinetyNine.value()),
            100 => self.pin.set_timestamp(Angle::OneHundred.value()),
            101 => self.pin.set_timestamp(Angle::OneHundredOne.value()),
            102 => self.pin.set_timestamp(Angle::OneHundredTwo.value()),
            103 => self.pin.set_timestamp(Angle::OneHundredThree.value()),
            104 => self.pin.set_timestamp(Angle::OneHundredFour.value()),
            105 => self.pin.set_timestamp(Angle::OneHundredFive.value()),
            106 => self.pin.set_timestamp(Angle::OneHundredSix.value()),
            107 => self.pin.set_timestamp(Angle::OneHundredSeven.value()),
            108 => self.pin.set_timestamp(Angle::OneHundredEight.value()),
            109 => self.pin.set_timestamp(Angle::OneHundredNine.value()),
            110 => self.pin.set_timestamp(Angle::OneHundredTen.value()),
            111 => self.pin.set_timestamp(Angle::OneHundredEleven.value()),
            112 => self.pin.set_timestamp(Angle::OneHundredTwelve.value()),
            113 => self.pin.set_timestamp(Angle::OneHundredThirteen.value()),
            114 => self.pin.set_timestamp(Angle::OneHundredFourteen.value()),
            115 => self.pin.set_timestamp(Angle::OneHundredFifteen.value()),
            116 => self.pin.set_timestamp(Angle::OneHundredSixteen.value()),
            117 => self.pin.set_timestamp(Angle::OneHundredSeventeen.value()),
            118 => self.pin.set_timestamp(Angle::OneHundredEighteen.value()),
            119 => self.pin.set_timestamp(Angle::OneHundredNineteen.value()),
            120 => self.pin.set_timestamp(Angle::OneHundredTwenty.value()),
            121 => self.pin.set_timestamp(Angle::OneHundredTwentyOne.value()),
            122 => self.pin.set_timestamp(Angle::OneHundredTwentyTwo.value()),
            123 => self.pin.set_timestamp(Angle::OneHundredTwentyThree.value()),
            124 => self.pin.set_timestamp(Angle::OneHundredTwentyFour.value()),
            125 => self.pin.set_timestamp(Angle::OneHundredTwentyFive.value()),
            126 => self.pin.set_timestamp(Angle::OneHundredTwentySix.value()),
            127 => self.pin.set_timestamp(Angle::OneHundredTwentySeven.value()),
            128 => self.pin.set_timestamp(Angle::OneHundredTwentyEight.value()),
            129 => self.pin.set_timestamp(Angle::OneHundredTwentyNine.value()),
            130 => self.pin.set_timestamp(Angle::OneHundredThirty.value()),
            131 => self.pin.set_timestamp(Angle::OneHundredThirtyOne.value()),
            132 => self.pin.set_timestamp(Angle::OneHundredThirtyTwo.value()),
            133 => self.pin.set_timestamp(Angle::OneHundredThirtyThree.value()),
            134 => self.pin.set_timestamp(Angle::OneHundredThirtyFour.value()),
            135 => self.pin.set_timestamp(Angle::OneHundredThirtyFive.value()),
            136 => self.pin.set_timestamp(Angle::OneHundredThirtySix.value()),
            137 => self.pin.set_timestamp(Angle::OneHundredThirtySeven.value()),
            138 => self.pin.set_timestamp(Angle::OneHundredThirtyEight.value()),
            139 => self.pin.set_timestamp(Angle::OneHundredThirtyNine.value()),
            140 => self.pin.set_timestamp(Angle::OneHundredFourty.value()),
            141 => self.pin.set_timestamp(Angle::OneHundredFourtyOne.value()),
            142 => self.pin.set_timestamp(Angle::OneHundredFourtyTwo.value()),
            143 => self.pin.set_timestamp(Angle::OneHundredFourtyThree.value()),
            144 => self.pin.set_timestamp(Angle::OneHundredFourtyFour.value()),
            145 => self.pin.set_timestamp(Angle::OneHundredFourtyFive.value()),
            146 => self.pin.set_timestamp(Angle::OneHundredFourtySix.value()),
            147 => self.pin.set_timestamp(Angle::OneHundredFourtySeven.value()),
            148 => self.pin.set_timestamp(Angle::OneHundredFourtyEight.value()),
            149 => self.pin.set_timestamp(Angle::OneHundredFourtyNine.value()),
            150 => self.pin.set_timestamp(Angle::OneHundredFifty.value()),
            151 => self.pin.set_timestamp(Angle::OneHundredFiftyOne.value()),
            152 => self.pin.set_timestamp(Angle::OneHundredFiftyTwo.value()),
            153 => self.pin.set_timestamp(Angle::OneHundredFiftyThree.value()),
            154 => self.pin.set_timestamp(Angle::OneHundredFiftyFour.value()),
            155 => self.pin.set_timestamp(Angle::OneHundredFiftyFive.value()),
            156 => self.pin.set_timestamp(Angle::OneHundredFiftySix.value()),
            157 => self.pin.set_timestamp(Angle::OneHundredFiftySeven.value()),
            158 => self.pin.set_timestamp(Angle::OneHundredFiftyEight.value()),
            159 => self.pin.set_timestamp(Angle::OneHundredFiftyNine.value()),
            160 => self.pin.set_timestamp(Angle::OneHundredSixty.value()),
            161 => self.pin.set_timestamp(Angle::OneHundredSixtyOne.value()),
            162 => self.pin.set_timestamp(Angle::OneHundredSixtyTwo.value()),
            163 => self.pin.set_timestamp(Angle::OneHundredSixtyThree.value()),
            164 => self.pin.set_timestamp(Angle::OneHundredSixtyFour.value()),
            165 => self.pin.set_timestamp(Angle::OneHundredSixtyFive.value()),
            166 => self.pin.set_timestamp(Angle::OneHundredSixtySix.value()),
            167 => self.pin.set_timestamp(Angle::OneHundredSixtySeven.value()),
            168 => self.pin.set_timestamp(Angle::OneHundredSixtyEight.value()),
            169 => self.pin.set_timestamp(Angle::OneHundredSixtyNine.value()),
            170 => self.pin.set_timestamp(Angle::OneHundredSeventy.value()),
            171 => self.pin.set_timestamp(Angle::OneHundredSeventyOne.value()),
            172 => self.pin.set_timestamp(Angle::OneHundredSeventyTwo.value()),
            173 => self.pin.set_timestamp(Angle::OneHundredSeventyThree.value()),
            174 => self.pin.set_timestamp(Angle::OneHundredSeventyFour.value()),
            175 => self.pin.set_timestamp(Angle::OneHundredSeventyFive.value()),
            176 => self.pin.set_timestamp(Angle::OneHundredSeventySix.value()),
            177 => self.pin.set_timestamp(Angle::OneHundredSeventySeven.value()),
            178 => self.pin.set_timestamp(Angle::OneHundredSeventyEight.value()),
            179 => self.pin.set_timestamp(Angle::OneHundredSeventyNine.value()),
            180 => self.pin.set_timestamp(Angle::OneHundredEighty.value()),
            _ => print!("Angle is out of bounds!")
        }
    }

    pub fn sweep(&mut self, delay: Delay) {
        for i in Angle::Zero.value()..Angle::OneHundredEighty.value() {
            self.pin.set_timestamp(i);
            delay.delay_millis(2_u32);
        }
    }
}
